### ISSUE TITLE
inside ... set ... to ... for ... не работает с конфигурацией солюшена по-умолчанию (пустой строкой)

### ISSUE THREAD

**Issue by Aggtaa** [TouchInstinct/BuildScript#36]
sln_config = "" генерирует ошибку regexp:

inside '{@csproj_dir}/{@csproj_path}' set CodesignKey to '{@provisioning_account}' for '{@sln_config}'

**Comment by rzaitov** [comment]
исправил. теперь если в качестве sln_config'а указана пустая строка замена будет производиться в PropertyGroup у которого нет тэга Condition
