### ISSUE TITLE
нужна команда для упаковки собранного андроид-проекта в APK файл

### ISSUE THREAD

**Issue by Aggtaa** [TouchInstinct/BuildScript#51]
"%paths.mdtool%" build "--target:SignAndroidPackage" --configuration:${config} "--project:${project}" "%project.sln.path%"

**Comment by rzaitov** [comment]
реализовано. синтаксис такой:
`sign    android 'BuildSample/BuildSample.sln' for '{@sln_config}' project 'DroidApp'`

Тесты не писал на это дело. Но проверил, работает
